## 인덱싱 ( indexing )

- ndrray에서 데이터를 검색하는 방법
- 인덱싱 방법
    | 종류 | 방법 | 특징 |
    |------|------|------|
    |단일값 인덱싱|arr[2] | 특정 위치 단일값 출력|
  |슬라이싱|arr[1:4]| 연속된 범위|
  |팬시 인덱싱 |arr[0, 2, 4] | 불연속 위치 다중값 출력|
  |불린 인덱싱 | arr [arr > 5] | 조건에 맞는 값 출력 |

### (1) 단일값 인덱싱

In [1]:
import numpy as np

In [3]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[2]

np.int64(3)

In [7]:
print(type(arr))
print(type(arr[2]))

print(arr.dtype)
print(arr[2].dtype)

print(arr.shape)
print (arr[2].shape)

<class 'numpy.ndarray'>
<class 'numpy.int64'>
int64
int64
(9,)
()


In [8]:
print(arr)
print(arr[0])
print(arr[3])
print(arr[5])
print(arr[-2])
print(arr[-5])

[1 2 3 4 5 6 7 8 9]
1
4
6
8
5


### (2) 값 변경

In [12]:
arr[0] = 100
print(arr)
arr[-1] = 900
print(arr)

[100   2   3   4   5   6   7   8   9]
[100   2   3   4   5   6   7   8 900]


### (3) 2차원 배열
- 2차원 배열은 [행, 열] 기준으로 검색

In [14]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr2 = np.reshape(arr, (3, 3))
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
print(arr2.shape)
print(arr2[0, 2])
print(arr2[2, 1])
print(arr2[1, 1])
print(arr2[-1, -1])

(3, 3)
3
8
5
9


### (4) 슬라이싱
- ' : ' 기호를 이용하여 연속된 데이터를 출력

In [19]:
array1 = np.arange(1, 10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
array1[0:3]

array([1, 2, 3])

In [26]:
print(array1[3:6])
print(array1[:3])
print(array1[::2])
print(array1[::-1])

[4 5 6]
[1 2 3]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1]


#### 2차원 슬라이싱

In [27]:
arr = np.arange(1, 10).reshape((3, 3))

In [29]:
print(arr[0:1, 0:3])
print(arr[0:2, 0:2])
print(arr[1:3, 1:3])
print(arr[:2, :3])

[[1 2 3]]
[[1 2]
 [4 5]]
[[5 6]
 [8 9]]
[[1 2 3]
 [4 5 6]]


In [31]:
print(arr[0], arr[0].shape)
print(arr[2], arr[2].shape)

[1 2 3] (3,)
[7 8 9] (3,)


### (5) 팬시 인덱싱
- 불연속적인 여러 위치의 값을 인덱싱하여 출력

#### - 1차원 배열의 팬시 인덱싱

In [32]:
array1 = np.arange(1, 10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
print(array1[0])
print(array1[0:3])
print(array1[[0, 2, 3]])

1
[1 2 3]
[1 3 4]


In [35]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
value = array1[4:][[2, 4]]
print(value, value.shape)

[7 9] (2,)


#### - 2차원 배열 팬시 인덱싱

In [37]:
arr = np.arange(1, 10).reshape((3, 3))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
print(arr[[0, 1], 2])
print(arr[[0, 2], 2])
print(arr[[0, 2], [1]])
print(arr[[0, 2], 1:2])

[3 6]
[3 9]
[2 8]
[[2]
 [8]]


### (6) 불린 인덱싱
- 조건식을 사용하여 인덱싱
- 데이터 필터링에 자주 사용됨

In [43]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr[arr > 5]

array([6, 7, 8, 9])

In [46]:
arr_bool = arr < 5
arr_bool

array([ True,  True,  True,  True, False, False, False, False, False])

In [49]:
arr_bool = arr > 5
print(arr)
print(arr_bool, arr[arr_bool], arr[arr > 5])

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True] [6 7 8 9] [6 7 8 9]


In [50]:
print(arr[arr%2 == 0])
print(arr[arr%2 == 1])

[2 4 6 8]
[1 3 5 7 9]


In [52]:
print(arr[(arr%2 == 0) | (arr%5 == 0)])

[2 4 5 6 8]


In [53]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
target = []
type(target)

list

In [62]:
target = []
for n in range(1, len(arr) + 1) :
    if n > 5 :
        target.append(n)
print(target, type(target))
arr2 = np.array(target)
print(arr2, type(arr2))

[6, 7, 8, 9] <class 'list'>
[6 7 8 9] <class 'numpy.ndarray'>


In [59]:
list(range(1, len(arr) + 1))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [64]:
arr1 = arr[arr  > 5]
print(arr1, type(arr1))

[6 7 8 9] <class 'numpy.ndarray'>


In [73]:
names = np.array(['진진', '뇽', '누리', '가나디', '고냐니'])
scores = np.array([80, 90, 100, 20, 50])

print(names [scores >= 80])

print(scores [scores >= 90])

['진진' '뇽' '누리']
[ 90 100]
